---
title: "*Coding Smart in Academia* PhD Project"
author: "Flic Anderson"
date: "21/11/2022"
output: 
  ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


<style>
  footer:after {
    content: attr(label);
    font-size: 12pt;
    position: absolute;
    bottom: 20px;
    left: 100px;
    line-height: 1.9;
  }
</style>

<style type="text/css">
slides > slide:not(.nobackground):after {
  content: '';
}
</style>

<div class="notes">

Bio: 
Currently a PhD Researcher at EPCC, School of Informatics, at the University of Edinburgh. 

Title: Coding Smart in Academia: Evidence-Based Software Engineering Approaches for High-Quality Research Software Projects

Abstract:  
This project will investigate which effective software engineering approaches (software engineering techniques and development practices) prevalent in traditional software engineering can be recommended to small research software projects to improve their software quality and development efficiency using empirical evidence from mixed methods approaches and novel software quality measurement frameworks
</div>



## PhD Project: 

 * **methods**: mining software repositories (github, zenodo), statistical methods for data analysis (inc. PCA or similar clustering analysis), software analysis tools, surveys/questionnaires  
 
 * **skills required**: software engineering, REST APIs, statistical analysis of data, data management, survey creation and data analysis,    
 
 * **challenges / risks**: 
   - difficulty estimating time to learn new skills  
   - survey setup/resppnse/completion time  
   - confirming developer roles in projects  
   - API limiting for large-scale analysis  



## RS Developer 'Personas'

<font size=6>"Are there differences in the way RS developers interact with a repo, and can repo activity and contributions help understand this?"</font> 

* Data collection, processing pipeline almost complete (Nov-Dec 2023); data analysis (Dec-Jan '24); write up (Jan-Mar '24)   

* Submit to _PeerJ Computer Science_ or _?Journal of Open Research Software?_ by Mar 2024    

* Short talk at _International Research Software Engineering Community Meet-up_ (16-17 Jan 2024); workshop/talk at _UK RSE_ Sept 2024; possibly _US RSE_ Oct 2024   


## RS Lifecycle +/ Release Practices  

**Qs:** "Does RS differ from traditional software or OSS in release activity? Does the RS lifecycle differ? Can repo mining describe 'typical' RS release practices?"   

* Data/APIs pipeline (Nov-Dec 2023); develop hypotheses/RQs (Mar '24), ?registered report initial report writing? (Mar-May),  explore code analysis tools, carry out study (June-July), write up findings (Aug-Dec '24)

* Submit (?registered report?) to _Empirical Software Engineering Journal_ by Nov/Dec 2024    

* Present at _Mining Software Repositories_ (MSR) ?Registered Report track? ~Apr 2025   


## RS Engineering Practices 

**Qs:** "Can software repository mining identify use of defensive programming concepts within RS? How well can 'RS quality' be assessed via identification of 'code smells' using tools from traditional software engineering or OSS?"  

* Data/APIs pipeline (Nov-Dec 2023); explore code analysis tools, carry out study (Dec '24 - Feb '25), write up (Feb-Apr '25)    

* Submit to _?Computing in Science and Engineering?_ by March/April 2025   

* ?Poster at _ICSE_ April 2025?    




## Progress this year  

* Further literature reading 
* Developed own research ideas and narrowed down RQs
* Exploration of github API data  
* Software engineering - learned python, built familiarity with APIs and data analysis, created data collection/processing pipeline  
* Demonstrating masters courses  
* Assisting on HPC summer school  


# Discussion  


## Key papers:  

* MSR: [Vidoni 2022 "A systematic process for Mining Software Repositories: Results from a systematic literature review"](https://doi.org/10.1016/j.infsof.2021.106791)  
* MSR: [Milewicz, Pinto & Rodeghero 2019 "Characterizing the Roles of Contributors in Open-Source Scientific Software Projects"](https://doi.org/10.1109/MSR.2019.00069)
* Survey: [Pinto et al 2018 "How do scientists develop scientific software? An external replication"](https://doi.org/10.1109/SANER.2018.8330263)  
* Survey [Hannay et al 2009 "How do scientists develop and use scientific software?"](https://doi.org/10.1109/SECSE.2009.5069155)


## Repo eligibility Pt 1 

**Dev Numbers:** repo has > 1 dev; repo has < 1000 devs

**Commits:** > 100-500 commits?

**Has PRs**

**Is RS**: (will be TRUE since the gh repo url should have come via zenodocode therefore has associated DOI)

**Issue Tickets**: uses issue tickets; has > 10 issue tickets

**Recent Activity:** has commit within last 12-18 months; has PR activity within last 12 months?


## Repo eligibility Pt. 2 
    
**Repo Age**: repo is established, >3 years old.

**Licence**: has open license

**Accessibility**: repo is set to public

**Repo Content**: repo contains code, not just docs or data; look for file endings.

**Repo Language**: contains some of: python, (shell?), (R?), java, C, C++